apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
#    access: proxy
#    url: http://localhost:8123
#    basicAuth: false
    isDefault: true
    jsonData:
      defaultDatabase: service_catalogs
      port: 9000
      host: clickhouse
      username: '${CLICKHOUSE_ADMIN_USER}'
    secureJsonData:
      password: '${CLICKHOUSE_ADMIN_PASSWORD}'